#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.

packages:
  - golang-go

# Sets the GOPATH & downloads the demo payload
runcmd:
  - export GOPATH=~/
  - go get github.com/hashicorp/learn-go-webapp-demo
